FROM node:22-alpine AS builder
WORKDIR /usr/app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM node:22-alpine
WORKDIR /app

ARG FIREBASE_PROJECT_ID
ARG FIREBASE_WEB_API_KEY
ARG WEBSITE_AUTH_BASE_URL
ARG GMAIL_USER
ARG GMAIL_APP_PASSWORD
ARG EMAIL_FROM_ALIAS
ARG NODE_ENV=production
ARG LOG_LEVEL=info
ARG PORT=8080
ARG HOST=0.0.0.0

ENV FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID
ENV FIREBASE_WEB_API_KEY=$FIREBASE_WEB_API_KEY
ENV WEBSITE_AUTH_BASE_URL=$WEBSITE_AUTH_BASE_URL
ENV GMAIL_USER=$GMAIL_USER
ENV GMAIL_APP_PASSWORD=$GMAIL_APP_PASSWORD
ENV EMAIL_FROM_ALIAS=$EMAIL_FROM_ALIAS
ENV NODE_ENV=$NODE_ENV
ENV LOG_LEVEL=$LOG_LEVEL
ENV PORT=$PORT
ENV HOST=$HOST

COPY --from=builder /usr/app/dist/. ./
COPY --from=builder /usr/app/node_modules ./node_modules
COPY --from=builder /usr/app/src/public ./public
EXPOSE 8080
CMD ["node", "server.js"]